---
title: "`r paste(lubridate::year(as.Date(SDATE,'%m/%d/%Y')),'LAKE SUPERIOR CREEL SURVEY')`"
params:
  FDATE:
    value: 09/30/2014
  FTYPE:
    value: SAS
  LOC:
    value: sup
  SDATE:
    value: 05/21/2014
  TABLES:
    value: !r c(1,2,3,4,5,6,7,8,9)
  FIGURES:
    value: !r c(1,2)
  WDIR:
    value: ""
  RDIR:
    value: ""
output:
  html_document:
    theme: sandstone
    css: tables.css
---

```{r input, echo=FALSE}
## Grab User's Inputs from parameters
LOC <- params$LOC
SDATE <- params$SDATE
FDATE <- params$FDATE
FTYPE <- params$FTYPE
TABLES <- params$TABLES
FIGURES <- params$FIGURES
WDIR <- params$WDIR
RDIR <- params$RDIR
```

```{r setup, include=FALSE, message=FALSE}
## Preliminaries
knitr::opts_chunk$set(echo=FALSE, results='asis', warning=FALSE, message=FALSE)

## Run the analysis
source(paste0(WDIR,"helpers/LSCreel_DataPrep.R"))
## Make table and figure captions
tables <- tableCaptions()
figures <- figureCaptions()
```

## `r paste("Report for",iMvLoc(LOC),"from",format(SDATE,format='%B %d, %Y'),"to",format(FDATE,format='%B %d, %Y'))`
#### Run on `r format(lubridate::now(),format="%B %d, %Y at %H:%M")`


```{r table1, eval=1 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table1"))
table1(fnpre,calSum)
```

```{r table2, eval=2 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table2"))
table2(fnpre,intvdEffortState)
```

```{r table3, eval=3 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table3"))
table3(fnpre,pressureCount)
```

```{r table4, eval=4 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table4"))
table4(fnpre)
```

```{r table5, eval=5 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table5"))
table5(fnpre)
```

```{r table6, eval=6 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table6"))
table6(fnpre)
```

```{r table7, eval=7 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table7"))
table7(fnpre)
```

```{r table8, eval=8 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table8"))
table8(fnpre)
```

```{r table9, eval=9 %in% TABLES}
cat("<br><br>")
cat("<hr>")
cat(tables("Table9"))
table9(fnpre)
```

```{r figure1, eval=1 %in% FIGURES, fig.width=5, fig.height=3.5}
cat("<br><br>")
cat("<hr>")
figure1(fnpre)
cat("<br>")
cat(figures("Figure1"))
```

```{r figure2, eval=2 %in% FIGURES, fig.width=7}
cat("<br><br>")
cat("<hr>")
figure2(fnpre)
cat("<br>")
cat(figures("Figure2"))
```

```{r figure3, eval=3 %in% FIGURES, fig.width=5, fig.height=3.5}
cat("<br><br>")
cat("<hr>")
figure3(fnpre)
cat("<br>")
cat(figures("Figure3"))
```

```{r figure4, eval=3 %in% FIGURES, fig.width=7, fig.height=8}
cat("<br><br>")
cat("<hr>")
figure4(fnpre)
cat("<br>")
cat(figures("Figure4"))
```

```{r}
cat("<br><br>")
cat("<hr>")
FSA::reproInfo(out="markdown",rqrdPkgs=rqrd,addTOC=FALSE)
```

