---
title: "LAKE SUPERIOR CREEL SURVEY"
params:
  LOC:
    value: sup
  SDATE:
    value: 05/21/2014
  FDATE:
    value: 09/30/2014
  DAY_LENGTH:
    value: NULL
  CNTS_FILE:
    value: NULL
  INTS_FILE:
    value: NULL
  TABLES:
    value: !r c(1)
  FIGURES:
    value: !r c(1)
  WDIR:
    value: ""
  RDIR:
    value: ""
output:
  html_document:
    theme: sandstone
    css: LS_Analysis_CSS.css
---

```{r input, echo=FALSE}
## Grab User's Inputs from parameters
LOC <- params$LOC
SDATE <- params$SDATE
FDATE <- params$FDATE
CNTS_FILE <- params$CNTS_FILE
INTS_FILE <- params$INTS_FILE
DAY_LENGTH <- params$DAY_LENGTH
TABLES <- params$TABLES
FIGURES <- params$FIGURES
WDIR <- params$WDIR
RDIR <- params$RDIR
```

```{r setup, include=FALSE, message=FALSE}
## Preliminaries
knitr::opts_chunk$set(echo=FALSE, results='asis', warning=FALSE, message=FALSE)

## Run the analysis
source(file.path(WDIR,"Helpers","LS_Analysis_DataPrep.R"))

## Make table and figure captions
tables <- tableCaptions()
figures <- figureCaptions()
```

## `r paste("Report for",iMvLoc(LOC),"from",format(SDATE,format='%B %d, %Y'),"to",format(FDATE,format='%B %d, %Y'))`
#### Run on `r format(lubridate::now(),format="%B %d, %Y at %H:%M")`


```{r table1}
cat("<br><br>")
cat("<hr>")
cat(tables("Table1"))
table1(fnpre,calSum)
```

```{r table2}
cat("<br><br>")
cat("<hr>")
cat(tables("Table2"))
table2(ints_NOFISH)
```

```{r table3}
cat("<br><br>")
cat("<hr>")
cat(tables("Table3"))
table3(pressureCount)
```

```{r table4}
cat("<br><br>")
cat("<hr>")
cat(tables("Table4"))
table4(fnpre)
```

```{r table5}
cat("<br><br>")
cat("<hr>")
cat(tables("Table5"))
table5(fnpre)
```

```{r table6}
cat("<br><br>")
cat("<hr>")
cat(tables("Table6"))
table6(lengths)
```

```{r table7}
cat("<br><br>")
cat("<hr>")
cat(tables("Table7"))
table7(lengths)
```

```{r table8}
cat("<br><br>")
cat("<hr>")
cat(tables("Table8"))
table8(lengths)
```

```{r fig.width=5, fig.height=3.5}
cat("<br><br>")
cat("<hr>")
figure1(ttlEffort)
cat("<br>")
cat(figures("Figure1"))
```

```{r fig.width=5, fig.height=8}
cat("<br><br>")
cat("<hr>")
figure2(ttlEffort)
cat("<br>")
cat(figures("Figure2"))
```

```{r fig.width=5, fig.height=3.5}
cat("<br><br>")
cat("<hr>")
figure3(ttlHarvest)
cat("<br>")
cat(figures("Figure3"))
```

```{r fig.width=7}
cat("<br><br>")
cat("<hr>")
figure4(ttlHarvest)
cat("<br>")
cat(figures("Figure4"))
```

```{r fig.width=5, fig.height=3.5}
cat("<br><br>")
cat("<hr>")
figure5(ttlHarvest)
cat("<br>")
cat(figures("Figure5"))
```

```{r fig.width=7, fig.height=8}
cat("<br><br>")
cat("<hr>")
figure6(lengths)
cat("<br>")
cat(figures("Figure6"))
```


```{r table9}
cat("<br><br>")
cat("<hr>")
cat(tables("Table9"))
table9(lengths)
```


```{r}
cat("<br><br>")
cat("<hr>")
FSA::reproInfo(out="markdown",rqrdPkgs=rqrd,addTOC=FALSE)
```

