---
title: "LAKE SUPERIOR ICE CREEL SURVEY"
params:
  LOC:
    value: ""
  LOC2:
    value: ""
  YR:
    value: NULL
  WDIR:
    value: ""
  RDIR:
    value: ""
output:
  html_document:
    theme: sandstone
    css: LS_Analysis_Reports.css
---

```{r input, echo=FALSE}
## Grab User's Inputs from parameters
LOC <- params$LOC
LOC2 <- params$LOC2
YR <- params$YR
WDIR <- params$WDIR
RDIR <- params$RDIR
```

```{r setup, include=FALSE, message=FALSE}
## Preliminaries
knitr::opts_chunk$set(echo=FALSE, results='asis', warning=FALSE, message=FALSE)

## Run the analysis
source(file.path(WDIR,"Helpers","LS_ICE_DataPrep.R"))

## Make table and figure captions
tables <- captioner::captioner(prefix="Table")

## FISHERYs to remove from tables
FISHERYS2remove4TABSFIGS=c('Pleasure','Tribal')
## Make table caption suffix
cap2 <- ""
if (all(FISHERYS2remove4TABSFIGS!="")) 
  cap2 <- paste0("These fishery types (",paste(FISHERYS2remove4TABSFIGS,collapse=', '),
          ") are not shown but may be represented in the 'All' fisheries category.")

## Helper function to remove repeat labels in a variable ... used to help the
## aesthetics of huxtables
iRemoveRepeatLabels <- function(data,var,other_vars="") {
  ifelse(!FSA::repeatedRows2Keep(data,cols2use=c(var,other_vars)),"",
         as.character(data[,var]))
}

## Helper to add final characteristics to all tables
iFinishTable <- function(h,labelsRow,labelsCol,tableWidth) {
  h <- h %>%
    # Line above top and below bottom of table
    set_top_border(row=1,col=everywhere,2) %>%
    set_bottom_border(row=final(),col=everywhere,2) %>%
    # Line below variable names
    set_bottom_border(row=labelsRow,col=everywhere,1) %>%
    # Bold rows and columns of labels
    set_bold(row=1:labelsRow,col=everywhere,TRUE) %>%
    set_bold(row=everywhere,col=1:labelsCol,TRUE) %>%
    # Set table width
    set_width(tableWidth)
  h
}
```

## `r paste("Report for",LOC,"from",YEAR)`
#### Run on `r format(lubridate::now(),format="%B %d, %Y at %H:%M")`


```{r table1}
table1 <- function(PC) {
  # Prepare data.frame for huxtable
  PC <- PC %>%
    ## Remove unneeded variables from pressureCount
    dplyr::select(-SURVEY,-ROUTE) %>%
    ## Remove records where there were no fishable days
    dplyr::filter(TTLDAYS>0) %>%
    dplyr::rename(ttlDays=TTLDAYS)
  
  ## Separate into weekdays and weekends
  tmp <- split(PC,PC$DAYTYPE,drop=TRUE)
  dts <- names(tmp)
  numdts <- length(dts)
  if (numdts>1) { 
    tmp <- dplyr::full_join(tmp[[1]],tmp[[2]],by=c("MONTH","SITE"))
  } else tmp <- tmp[[1]]
  ## So that they can be put side-by-side for the table
  tbl1 <- tmp %>%
    dplyr::select(-dplyr::starts_with("DAYTYPE")) %>%
    dplyr::arrange(MONTH,SITE) %>%
    # Remove repeated rows in MONTH variable
    dplyr::mutate(MONTH=iRemoveRepeatLabels(.,"MONTH"))
  ## Add spacer columns to make table look nice
  tbl1 <- tibble::add_column(tbl1,spc1="",
                      .after=which(names(tbl1) %in% c("cntdVeh","cntdVeh.x")))
  if ("cntdVeh.y" %in% names(tbl1)) {
    tbl1 <- tbl1 %>%
    tibble::add_column(.,spc2="",.after="cntdVeh.y") %>%
    tibble::add_column(.,spc3="",.after="ttlVeh.x")
  }
  ## Rows with a MONTH names (except first) will get extra space above
  spaceAbove <- which(tbl1$MONTH!="")[-1]

  ## Make the huxtable
  tbl2 <- as_hux(tbl1) %>%
    # Set all cell paddings
    set_all_padding(1) %>%
    set_right_padding(row=everywhere,col=everywhere,value=5) %>%
    set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
    # Convert NAs to dashes
    set_na_string(row=everywhere,col=-(1:2),value="--") %>%
    # right align all but leftmost two columns
    set_align(row=everywhere,col=-(1:2),value="right") %>%
    # No decimals for observed values and total days
    set_number_format(row=everywhere,col=contains("Days"),value=0) %>%
    set_number_format(row=everywhere,col=contains("cntdVeh"),value=0) %>%
    set_number_format(row=everywhere,col=contains("ttlVeh"),value=1)
  # Extra label at the top
  if (numdts==1) {
    tbl2 <- tbl2 %>%
      rbind(c("MONTH","SITE","Days","Vehicles","","Days","Vehicles"),.) %>%
      rbind(c("","","Counted","","","Total",""),.) %>%
      rbind(c("","",unique(as.character(PC$DAYTYPE)),"","","",""),.)
  } else {
    tbl2 <- tbl2 %>%
      rbind(c("MONTH","SITE","Days","Vehicles","","Days","Vehicles","",
              "Days","Vehicles","","Days","Vehicles"),.) %>%
      rbind(c("","","Counted","","","Total","","","Counted","","","Total",""),.) %>%
      rbind(c("","","Weekdays","","","","","","Weekends","","","",""),.)
  }
  # Adjust headers
  for (i in 1:numdts) {
    cols <- (3:7)+(i-1)*6
    tbl2 <- merge_cells(tbl2,row=1,col=cols) %>%
      set_bottom_border(row=1,col=cols[1],value=1) %>%
      merge_cells(row=2,col=cols[1:2]) %>%
      set_bottom_border(row=2,col=cols[1],value=1) %>%
      merge_cells(row=2,col=cols[4:5]) %>%
      set_bottom_border(row=2,col=cols[4],value=1)
  }
  tbl2 <- tbl2 %>%
    set_align(row=1,col=everywhere,value="center") %>%
    set_align(row=2,col=everywhere,value="center")
  # Sets table & column widths
  cw <- c(.1,.35,.1,.1,.025,.1,.1)
  if (numdts>1) cw <- c(cw,.075,.1,.1,.025,.1,.1)
  tbl2 <- set_col_width(tbl2,col=cw) %>%
    iFinishTable(labelsRow=3,labelsCol=2,tableWidth=0.9)
  ## Return the huxtable
  tbl2
}

tables(name="Table1",display=FALSE,
       caption=paste("Number of pressure counts and number of observed",
                     "(i.e., counted) vehicles in those counts and total",
                     "fishable days and estimated total (i.e., expanded)",
                     "number of vehicles at each site by month and day type."))
cat("<br><br>")
cat("<hr>")
cat(tables("Table1"))

# Compare this to 'ICE CREEL MONTHLY PRESSURE' Excel file.
table1(pressureCount)
```

```{r table2}
table2 <- function(f,rmvFISHERYS="") {
  # Prepare data.frame for huxtable
  f <- f %>%
    ## Remove the unwanted fisheries
    dplyr::filter(!FISHERY %in% rmvFISHERYS) %>%
    ## change proportion to a percentage
    dplyr::mutate(pIntsInFishery=100*pIntsInFishery) %>%
    ## get rid of records for which it was not possible to observe vehicles
    dplyr::filter(!is.na(ttlVehSite))
  ## Just results by the site (across all fisheries)
  tmp1 <- dplyr::select(f,-NINTS,-pIntsInFishery,-ttlVehSiteFshry)
  ## Just the results by the fisherys (but not the total)
  tmp2 <- dplyr::select(f,-TTLINTS,-ttlVehSite)
  ## Split into fisheries so they can be put side-by-side
  tmp3 <- split(tmp2,tmp2$FISHERY,drop=TRUE)
  fshrys <- names(tmp3)
  numf <- length(fshrys)
  bys <- c("SURVEY","ROUTE","UNIT","MONTH","DAYTYPE","SITE")
  tmp4 <- tmp3[[1]]
  if (numf>1) for (i in 2:numf) tmp4 <- dplyr::full_join(tmp4,tmp3[[i]],by=bys)
  ## Join on total columns at end, clean up, and sort
  tbl1 <- dplyr::full_join(tmp4,tmp1,by=bys) %>%
    dplyr::select(-dplyr::starts_with("FISHERY"),-SURVEY,-ROUTE,-UNIT) %>%
    dplyr::filter(!duplicated(.)) %>%
    dplyr::arrange(MONTH,DAYTYPE,SITE) %>%
    # Remove repeated rows in MONTH and DAYTYPE variables
    dplyr::mutate(MONTH=iRemoveRepeatLabels(.,"MONTH"),
                  DAYTYPE=iRemoveRepeatLabels(.,"DAYTYPE","MONTH"))
  ## Add spacing columns so that the table looks nice
  acs <- which(grepl("ttlVehSiteFshry",names(tbl1)))
  for (i in rev(acs)) {
    tbl1 <- tibble::add_column(tbl1,"",.after=i)
    names(tbl1)[i+1] <- paste0("spc",i)
  }
  ## Prepare to add spaces above daytype changes
  spaceAbove <- which(tbl1$DAYTYPE!="")[-1]

  ## Prepare the top label for the table
  toplbl <- c("","","")
  for (i in fshrys) toplbl <- c(toplbl,i,"","","")
  toplbl <- c(toplbl,"Total","")

  ## Make the huxtable
  tbl2 <- as_hux(tbl1) %>%
    # Set all cell paddings
    set_all_padding(1) %>%
    set_right_padding(row=everywhere,col=everywhere,value=5) %>%
    set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
    # Convert NAs to dashes
    set_na_string(row=everywhere,col=-(1:3),value="--") %>%
    # right align all but leftmost three columns
    set_align(row=everywhere,col=-(1:3),value="right") %>%
    # No decimals for observed values and total days
    set_number_format(row=everywhere,col=contains("INTS"),value=0) %>%
    set_number_format(row=everywhere,col=contains("ttlVeh"),value=1) %>%
    set_number_format(row=everywhere,col=contains("pInts"),value=0) %>%
    # Extra label at the top
    rbind(c("MONTH","DAYTYPE","SITE",
            rep(c("N","P","Veh",""),numf),
            "N","Veh"),.) %>%
    rbind(toplbl,.)
  # Adjust headers
  for (i in 1:numf) {
    cols <- (4:6)+(i-1)*4
    tbl2 <- merge_cells(tbl2,row=1,col=cols) %>%
      set_bottom_border(row=1,col=cols[1],value=1)
  }
  tbl2 <- tbl2 %>%
    merge_cells(row=1,col=(0:1)+(numf+1)*4) %>%
    set_bottom_border(row=1,col=(numf+1)*4,value=1) %>%
    set_align(row=1,col=everywhere,value="center") %>%
    # Sets column widths
    set_col_width(col=c(.1,.1,.35,
                        rep(c(0.1,0.1,0.1,0.025),numf),
                        .1,.1)) %>%
    iFinishTable(labelsRow=2,labelsCol=3,tableWidth=0.99)

  ## Return the huxtable
  tbl2  
}

tables(name="Table2",display=FALSE,
       caption=paste("Number of interviews (N), percent of interviews (P) at",
                     "that site in each fishery type, and estimated total",
                     "(i.e., expanded) number of vehicles (Veh) in each fishery",
                     "and across all fishery types at each site by month",
                     "and day type.",cap2))

cat("<br><br>")
cat("<hr>")
cat(tables("Table2"))

# Compare this to 'ICE CREEL EXPANDED PRESSURE' Excel file.
table2(ttlEffortBySite,FISHERYS2remove4TABSFIGS)
```

```{r table3}
table3 <- function(sumExpHarvAll,rmvFISHERYS="") {
  # Prepare data.frame for huxtable
tbl1 <- sumExpHarvAll %>%
  ## Remove unwanted fisheries
  dplyr::filter(!FISHERY %in% rmvFISHERYS) %>%
  dplyr::select(UNIT,FISHERY,MONTH,DAYTYPE,
                ttlVehFshry,anglersPerInt,ttlAnglers,
                avgAnglerHours,ttlAnglerHours,percSucc,ttlSuccAnglers,
                harvestRate,ttlHarvest) %>%
  dplyr::arrange(UNIT,FISHERY,MONTH,DAYTYPE) %>%
  # Remove repeated rows in MONTH and FISHERY variables
  dplyr::mutate(UNIT=iRemoveRepeatLabels(.,"UNIT"),
                FISHERY=iRemoveRepeatLabels(.,"FISHERY"),
                MONTH=iRemoveRepeatLabels(.,"MONTH")) %>%
  ## Remove rows that are repeats (for the numerics) of the row above it and
  ## if DAYTYPE=="All" (i.e., "All" is just for one daytype).
  dplyr::filter(!(!FSA::repeatedRows2Keep(.,
                            cols2ignore=c("UNIT","FISHERY","MONTH","DAYTYPE")) &
                DAYTYPE=="All"))

## Rows with a FISHERY names (except first) will get extra space above
spaceAbove <- which(tbl1$FISHERY!="")[-1]
## Rows with a DAYTYPE=="All" (except lasst) will get extra space below
spaceBelow <- which(tbl1$DAYTYPE=="All")
spaceBelow <- spaceBelow[-length(spaceBelow)]

## Make the huxtable
tbl2 <- as_hux(tbl1) %>%
  # Set all cell paddings
  set_all_padding(1) %>%
  set_right_padding(row=everywhere,col=everywhere,value=5) %>%
  set_top_padding(row=spaceAbove,col=everywhere,value=25) %>%
  set_bottom_padding(row=spaceBelow,col=everywhere,value=5) %>%
  # Convert NAs to dashes
  set_na_string(row=everywhere,col=-(1:4),value="--") %>%
  # right align all but leftmost thre columns
  set_align(row=everywhere,col=-(1:4),value="right") %>%
  # contol decimals
  set_number_format(row=everywhere,col=c(5,7,9,11,13),value=0) %>%
  set_number_format(row=everywhere,col=10,value=1) %>%
  set_number_format(row=everywhere,col=c(6,8),value=2) %>%
  set_number_format(row=everywhere,col=12,value=4) %>%
  # Extra label at the top
  rbind(c("UNIT","FISHERY","MONTH","DAYTYPE","Vehicles","per Int","Anglers",
          "Hours","Angler Hrs","Success","Anglers","Rate","Harvest"),.) %>%
  rbind(c("","","","","Total","Angler","Total",
          "Avg","Total","Perc","Success","Harvest","Total"),.) %>%
  set_align(row=1:2,col=everywhere,value="center") %>%
  # Set column widths
  set_col_width(col=c(.1,.2,.1,.1,.1,.1,.1,.1,.1,.1,.1,.1,.1)) %>%
  iFinishTable(labelsRow=2,labelsCol=4,tableWidth=0.9)
tbl2
}

tables(name="Table3",display=FALSE,
       caption=paste("Total effort and harvest summary for All Fish combined",
                     "by unit, fishery type, month, and day type.",cap2))

cat("<br><br>")
cat("<hr>")
cat(tables("Table3"))

# Compare this to columns A-K of 'ICE CREEL HARVEST' Excel file.
table3(sumExpHarvAll,FISHERYS2remove4TABSFIGS)
```

```{r table4}
table4 <- function(sumExpHarvSPP,rmvFISHERYS="") {
  # Prepare data.frame for huxtable
  H <- sumExpHarvSPP %>%
    ## Remove unwanted fisheries
    dplyr::filter(!FISHERY %in% rmvFISHERYS) %>%
    ## Remove unneeded variables
    dplyr::select(-SURVEY,-ROUTE)
  ## Split by DAYTYPEs so that they can be side-by-side
  tmp <- split(H,H$DAYTYPE,drop=TRUE)
  ds <- names(tmp)
  numds <- length (ds)
  tmp1 <- tmp[[1]]
  if (numds>1) 
    for (i in 2:numds)
      tmp1 <- dplyr::full_join(tmp1,tmp[[i]],by=c("UNIT","SPECIES","FISHERY","MONTH"))

  tbl1 <- tmp1 %>%
    dplyr::select(-dplyr::starts_with("DAYTYPE")) %>%
    dplyr::filter(!is.na(SPECIES)) %>%
    dplyr::mutate(SPECIES=factor(SPECIES,levels=lvlsSPECIES)) %>%
    dplyr::arrange(SPECIES,FISHERY,MONTH) %>%
    ## Add aesthetic spacing columns (for huxtable)
    tibble::add_column(.,spc1="",.after="ttlHarvest.x")
  ## this is needed as some routes don't have harvest on both daytypes
  if (numds>2) tbl1 <- tibble::add_column(tbl1,spc2="",.after="ttlHarvest.y")
  ## Drop the "All" FISHERYs for species in a unit captured in only one fishery
  ## (note the use of 2 in the filter because of an "All" fishery)
  SPP2dropAll <- dplyr::group_by(tbl1,UNIT,SPECIES) %>%
    dplyr::summarize(numFshrys=length(unique(FISHERY))) %>%
    dplyr::filter(numFshrys==2)
  tbl1 <- dplyr::filter(tbl1,!(UNIT %in% SPP2dropAll$UNIT &
                                 SPECIES %in% SPP2dropAll$SPECIES &
                                 FISHERY=="All"))
  ## Drop the "All" MONTHs for species in a unit captured in only one month
  ## (note the use of 2 in the filter because of an "All" MONTH)
  SPP2dropAll <- dplyr::group_by(tbl1,UNIT,SPECIES) %>%
    dplyr::summarize(numMons=length(unique(MONTH))) %>%
    dplyr::filter(numMons==2)
  tbl1 <- dplyr::filter(tbl1,!(UNIT %in% SPP2dropAll$UNIT &
                                 SPECIES %in% SPP2dropAll$SPECIES &
                                 MONTH=="All"))
  ## Remove repeated rows in UNIT, SPECIES, FISHERY, MONTH variables
  ##   This makes the table look nicer
  tbl1 <- tbl1 %>%
          dplyr::mutate(UNIT=iRemoveRepeatLabels(.,"UNIT"),
                        SPECIES=iRemoveRepeatLabels(.,"SPECIES"),
              ## Use of UNIT, SPECIES and FISHERY (rather than just FISHERY) guards
              ## against cutting a FISHERY across species
              FISHERY=iRemoveRepeatLabels(.,"FISHERY",c("UNIT","SPECIES")),
              MONTH=iRemoveRepeatLabels(.,"MONTH",c("UNIT","SPECIES")))
  ## Rows with a SPECIES name (except first) will get extra space above
  spaceAbove <- which(tbl1$SPECIES!="")[-1]

  toplbl <- c("","","","")
  for (i in ds) toplbl <- c(toplbl,i,"","")
  toplbl <- toplbl[-length(toplbl)]

  ## Make the huxtable
  tbl2 <- as_hux(tbl1) %>%
    # Set all cell paddings
    set_all_padding(1) %>%
    set_right_padding(row=everywhere,col=everywhere,value=5) %>%
    set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
    # Convert NAs to dashes
    set_na_string(row=everywhere,col=-(1:4),value="--") %>%
    # right align all but leftmost two columns
    set_align(row=everywhere,col=-(1:4),value="right") %>%
    # No decimals for harvest rates, four for harvest rate
    set_number_format(row=everywhere,col=contains("Harvest"),value=0) %>%
    set_number_format(row=everywhere,col=contains("Rate"),value=4) %>%
    # Extra label at the top
    rbind(c("UNIT","SPECIES","FISHERY","MONTH",rep(c("Rate","Harvest",""),numds-1),
            "Rate","Harvest"),.) %>%
    rbind(c("","","","",rep(c("Harvest","Total",""),numds-1),"Harvest","Total"),.) %>%
    rbind(toplbl,.)
  # Adjust headers
  for (i in 1:numds) {
    cols <- (5:6)+(i-1)*3
    tbl2 <- merge_cells(tbl2,row=1,col=cols) %>%
      set_bottom_border(row=1,col=cols[1],value=1)
  }

  tbl2 <- tbl2 %>%
    set_align(row=1,col=everywhere,value="center") %>%
    # Set column widths
    set_col_width(col=c(.1,.2,.3,.1,rep(c(.15,.1,.025),numds-1),.15,.1)) %>%
    iFinishTable(labelsRow=3,labelsCol=4,tableWidth=0.99)
  ## Return huxtable
  tbl2
}

tables(name="Table4",display=FALSE,
       caption=paste("Harvest rate and total harvest by unit,species, fishery,",
                     "month, and daytype. Note that 'All' is shown for the",
                     "fishery only for species caught in more than one",
                     "fishery.",cap2))

cat("<br><br>")
cat("<hr>")
cat(tables("Table4"))

#  Compare this to columns L-AD of 'ICE CREEL HARVEST' Excel file.
table4(sumExpHarvSPP,FISHERYS2remove4TABSFIGS)
```

```{r table5}
table5 <- function(sumLen,rmvFISHERYS="") {
  # Prepare data.frame for huxtable
  ## Remove unwanted fisheries
  sumLen <- dplyr::filter(sumLen,!FISHERY %in% rmvFISHERYS)
  tmp1 <- split(sumLen,sumLen$FISHERY,drop=TRUE)
  fshrys <- names(tmp1)
  numf <- length(fshrys)
  bys <- c("SURVEY","ROUTE","UNIT","SPECIES","MONTH","ORIGIN")
  tmp2 <- dplyr::full_join(tmp1[[1]],tmp1[[2]],by=bys)
  if (numf>2) for (i in 3:numf) tmp2 <- dplyr::full_join(tmp2,tmp1[[i]],by=bys)

  tbl1 <- tmp2 %>%
    dplyr::select(-SURVEY,-ROUTE,-starts_with("FISHERY")) %>%
    dplyr::select(UNIT,SPECIES,MONTH,ORIGIN,everything()) %>%
    dplyr::filter(!duplicated(.)) %>%
    dplyr::mutate(SPECIES=factor(SPECIES,levels=lvlsSPECIES)) %>%
    dplyr::arrange(UNIT,SPECIES,MONTH,ORIGIN)

  ## Drop the "All" ORIGINs for species have only one ORIGIN
  ## (note the use of 2 in the filter because of an "All" ORIGIN)
  SPP2dropAll <- dplyr::group_by(tbl1,UNIT,SPECIES) %>%
    dplyr::summarize(numOrigins=length(unique(ORIGIN))) %>%
    dplyr::filter(numOrigins==2)
  tbl1 <- dplyr::filter(tbl1,!(UNIT %in% SPP2dropAll$UNIT &
                                 SPECIES %in% SPP2dropAll$SPECIES &
                                 ORIGIN=="All"))

  ## Drop the "All" MONTHs for species have only one MONTH
  ## (note the use of 2 in the filter because of an "All" MONTH)
  SPP2dropAll <- dplyr::group_by(tbl1,UNIT,SPECIES) %>%
    dplyr::summarize(numMons=length(unique(MONTH))) %>%
    dplyr::filter(numMons==2)
  tbl1 <- dplyr::filter(tbl1,!(UNIT %in% SPP2dropAll$UNIT &
                                 SPECIES %in% SPP2dropAll$SPECIES &
                                 MONTH=="All"))

## Remove repeated rows in UNIT, SPECIES, MONTH and ORIGIN variables
tbl1 <- tbl1 %>%
  dplyr::mutate(UNIT=iRemoveRepeatLabels(.,"UNIT"),
                SPECIES=iRemoveRepeatLabels(.,"SPECIES"),
                MONTH=iRemoveRepeatLabels(.,"MONTH",c("UNIT","SPECIES")))

## Add extra columns for aesthetics in huxtable
acs <- which(grepl("maxLen",names(tbl1)))
for (i in rev(acs[-length(acs)])) {
  tbl1 <- tibble::add_column(tbl1,"",.after=i)
  names(tbl1)[i+1] <- paste0("spc",i)
}

spaceAbove <- which(tbl1$SPECIES!="")[-1]

toplbl <- c("","","","")
for (i in fshrys) toplbl <- c(toplbl,i,"","","","","")
toplbl <- toplbl[-length(toplbl)]

tbl2 <- as_hux(tbl1) %>%
  # Set all cell paddings
  set_all_padding(1) %>%
  set_right_padding(row=everywhere,col=everywhere,value=5) %>%
  set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
  # Convert NAs to dashes
  set_na_string(row=everywhere,col=-(1:4),value="--") %>%
  # right align all but leftmost three columns
  set_align(row=everywhere,col=-(1:4),value="right") %>%
  # Set decimals
  set_number_format(row=everywhere,col=starts_with("n"),value=0) %>%
  set_number_format(row=everywhere,col=contains("Len"),value=1) %>%
  # Extra label at the top
  rbind(c("UNIT","SPECIES","MONTH","ORIGIN",
          rep(c("n","Mean","SD","Min","Max",""),numf-1),
          "n","Mean","SD","Min","Max"),.) %>%
  rbind(toplbl,.)
# Adjust headers
for (i in 1:numf) {
  cols <- (5:9)+(i-1)*6
  tbl2 <- merge_cells(tbl2,row=1,col=cols) %>%
    set_bottom_border(row=1,col=cols[1],value=1)
}
tbl2 <- tbl2 %>%
  set_align(row=1,col=everywhere,value="center") %>%
  # Set column widths
  set_col_width(col=c(.1,.2,.1,.1,
                      rep(c(0.1,0.1,0.1,0.1,0.1,0.025),numf-1),
                      0.1,0.1,0.1,0.1,0.1)) %>%
  iFinishTable(labelsRow=2,labelsCol=4,tableWidth=0.99)
tbl2
}

tables(name="Table5",display=FALSE,
       caption=paste("Number of fish measured for length and mean, standard",
                     "deviation (SD), minimum, and maximum total length",
                     "(in.) by unit, species, month, origin (native or hatchery)",
                     "and fishery type. Note that 'All' is shown only for",
                     "months and origins where more than one month or origin",
                     "was observed.",cap2))

cat("<br><br>")
cat("<hr>")
cat(tables("Table5"))

#  Compare this to 'ICE CREEL CATCH AVE' Excel file.
table5(sumLen,FISHERYS2remove4TABSFIGS)
```


```{r}
cat("<br><br>")
cat("<hr>")
FSA::reproInfo(out="markdown",rqrdPkgs=rqrd,addTOC=FALSE)
```
