---
title: "LAKE SUPERIOR ICE CREEL SURVEY"
params:
  LOC:
    value: Ashland
  WDIR:
    value: ""
  RDIR:
    value: ""
output:
  html_document:
    theme: sandstone
    css: LS_Open_Analysis.css
---

```{r input, echo=FALSE}
## Grab User's Inputs from parameters
LOC <- params$LOC
WDIR <- params$WDIR
RDIR <- params$RDIR
```

```{r setup, include=FALSE, message=FALSE}
## Preliminaries
knitr::opts_chunk$set(echo=FALSE, results='asis', warning=FALSE, message=FALSE)

## Run the analysis
source(file.path(WDIR,"Helpers","LS_ICE_DataPrep.R"))

## Make table and figure captions
tables <- captioner::captioner(prefix="Table")

## Helper to add final characteristics to all tables
iFinishTable <- function(h,labelsRow,labelsCol) {
  h <- h %>%
    # Line above top and below bottom of table
    set_top_border(row=1,col=everywhere,2) %>%
    set_bottom_border(row=final(),col=everywhere,2) %>%
    # Line below variable names
    set_bottom_border(row=labelsRow,col=everywhere,1) %>%
    # Bold rows and columns of labels
    set_bold(row=1:labelsRow,col=everywhere,TRUE) %>%
    set_bold(row=everywhere,col=1:labelsCol,TRUE)
  h
}
```

## `r paste("Report for",LOC,"from",YEAR)`
#### Run on `r format(lubridate::now(),format="%B %d, %Y at %H:%M")`


```{r table1}
tables(name="Table1",display=FALSE,
       caption=paste("Number of pressure counts and number of observed",
                     "(i.e., counted) vehicles in those counts and total",
                     "fishable days and estimated total (i.e., expanded)",
                     "number of vehicles at each site by month and day type.",
                     "Compare this to 'ICE CREEL MONTHLY PRESSURE' Excel file."))
cat("<br><br>")
cat("<hr>")
cat(tables("Table1"))

## Prepare data.frame for huxtable
PC <- dplyr::select(pressureCount,-SURVEY,-ROUTE)
tmp1 <- dplyr::filter(PC,DAYTYPE=="Weekday") %>%
  dplyr::select(-DAYTYPE)
tmp2 <- dplyr::filter(PC,DAYTYPE=="Weekend") %>%
  dplyr::select(-DAYTYPE)
tbl1 <- dplyr::full_join(tmp1,tmp2,by=c("MONTH","SITE")) %>%
  arrange(MONTH,SITE) %>%
  dplyr::mutate(# Remove repeated rows in MONTH variable
                MONTH=ifelse(!FSA::repeatedRows2Keep(.,cols2use="MONTH"),
                             "",as.character(MONTH))) %>%
  tibble::add_column(.,spc1="",.after="cntdVeh.x") %>%
  tibble::add_column(.,spc2="",.after="cntdVeh.y") %>%
  tibble::add_column(.,spc3="",.after="ttlVeh.x")
## Rows with a MONTH names (except first) will get extra space above
spaceAbove <- which(tbl1$MONTH!="")[-1]

## Make the huxtable
tbl2 <- as_hux(tbl1) %>%
  # Set all cell paddings
  set_all_padding(1) %>%
  set_right_padding(row=everywhere,col=everywhere,value=5) %>%
  set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
  # Convert NAs to dashes
  set_na_string(row=everywhere,col=-(1:2),value="--") %>%
  # right align all but leftmost two columns
  set_align(row=everywhere,col=-(1:2),value="right") %>%
  # No decimals for observed values and total days
  set_number_format(row=everywhere,col=c(3:4,6,9:10,12),value=0) %>%
  set_number_format(row=everywhere,col=c(7,13),value=1) %>%
  # Extra label at the top
  rbind(c("MONTH","SITE",rep(c("Days","Vehicles",""),3),"Days","Vehicles"),.) %>%
  rbind(c("","","Counted","","","Total","","","Counted","","","Total",""),.) %>%
  rbind(c("","","Weekdays","","","","","","Weekends","","","",""),.) %>%
  # Adjust headers
  merge_cells(row=1,col=3:7) %>%
  set_bottom_border(row=1,col=3,value=1) %>%
  merge_cells(row=1,col=9:13) %>%
  set_bottom_border(row=1,col=9,value=1) %>%
  set_align(row=1,col=everywhere,value="center") %>%
  merge_cells(row=2,col=3:4) %>%
  set_bottom_border(row=2,col=3,value=1) %>%
  merge_cells(row=2,col=6:7) %>%
  set_bottom_border(row=2,col=6,value=1) %>%
  merge_cells(row=2,col=9:10) %>%
  set_bottom_border(row=2,col=9,value=1) %>%
  merge_cells(row=2,col=12:13) %>%
  set_bottom_border(row=2,col=12,value=1) %>%
  set_align(row=2,col=everywhere,value="center") %>%
  # Sets table & column widths
  set_width(0.9) %>%
  set_col_width(col=c(.1,.35,.1,.1,.025,.1,.1,.075,.1,.1,.025,.1,.1)) %>%
  iFinishTable(labelsRow=3,labelsCol=2)

## Show the huxtable
tbl2
```

```{r table2}
tables(name="Table2",display=FALSE,
       caption=paste("Number of interviews (N), percent of interviews (P) at",
                     "that site in each fishery type, and estimated total",
                     "(i.e., expanded) number of vehicles (Veh) in each fishery",
                     "and across all fishery types at each site by month",
                     "and day type. Compare this to 'ICE CREEL EXPANDED",
                     "PRESSURE' Excel file."))

cat("<br><br>")
cat("<hr>")
cat(tables("Table2"))

## Prepare data.frame for huxtable
fshrys <- unique(pcSite$FISHERY)
numf <- length(fshrys)
bys <- c("SURVEY","ROUTE","UNIT","MONTH","DAYTYPE","SITE")
PC <- mutate(pcSite,pIntsInFishery=100*pIntsInFishery)
tmp1 <- dplyr::select(PC,-NINTS,-pIntsInFishery,-ttlVehSiteFshry)
tmp2 <- dplyr::select(PC,-TTLINTS,-ttlVehSite)
tmp3 <- split(tmp2,tmp2$FISHERY)
tmp4 <- dplyr::full_join(tmp3[[1]],tmp3[[2]],by=bys)
for (i in 3:length(tmp3)) {
  tmp4 <- dplyr::full_join(tmp4,tmp3[[i]],by=bys)
}
tbl1 <- dplyr::full_join(tmp4,tmp1,by=bys) %>%
  dplyr::select(-dplyr::starts_with("FISHERY"),-SURVEY,-ROUTE,-UNIT) %>%
  dplyr::filter(!duplicated(.)) %>%
  dplyr::arrange(MONTH,DAYTYPE,SITE) %>%
  # Remove repeated rows in MONTH and DAYTYPE variables
  dplyr::mutate(MONTH=ifelse(!FSA::repeatedRows2Keep(.,cols2use="MONTH"),
                             "",as.character(MONTH)),
                DAYTYPE=ifelse(!FSA::repeatedRows2Keep(.,cols2use="DAYTYPE"),
                               "",as.character(DAYTYPE)))

acs <- which(grepl("ttlVehSiteFshry",names(tbl1)))
for (i in rev(acs)) {
  tbl1 <- tibble::add_column(tbl1,"",.after=i)
  names(tbl1)[i+1] <- paste0("spc",i)
}

spaceAbove <- which(tbl1$DAYTYPE!="")[-1]

toplbl <- c("","","")
for (i in fshrys) toplbl <- c(toplbl,i,"","","")
toplbl <- c(toplbl,"Total","")

tbl2 <- as_hux(tbl1) %>%
  # Set all cell paddings
  set_all_padding(1) %>%
  set_right_padding(row=everywhere,col=everywhere,value=5) %>%
  set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
  # Convert NAs to dashes
  set_na_string(row=everywhere,col=-(1:3),value="--") %>%
  # right align all but leftmost three columns
  set_align(row=everywhere,col=-(1:3),value="right") %>%
  # No decimals for observed values and total days
  set_number_format(row=everywhere,col=contains("INTS"),value=0) %>%
  set_number_format(row=everywhere,col=contains("ttlVeh"),value=1) %>%
  set_number_format(row=everywhere,col=contains("pInts"),value=0) %>%
  # Extra label at the top
  rbind(c("MONTH","DAYTYPE","SITE",
          rep(c("N","P","Veh",""),numf),
          "N","Veh"),.) %>%
  rbind(toplbl,.)
# Adjust headers
for (i in 1:numf) {
  cols <- (4:6)+(i-1)*4
  tbl2 <- merge_cells(tbl2,row=1,col=cols) %>%
    set_bottom_border(row=1,col=cols[1],value=1)
}
tbl2 <- tbl2 %>%
  merge_cells(row=1,col=(0:1)+(numf+1)*4) %>%
  set_bottom_border(row=1,col=(numf+1)*4,value=1) %>%
  set_align(row=1,col=everywhere,value="center") %>%
  # Sets table & column widths
  set_width(0.99) %>%
  set_col_width(col=c(.1,.1,.35,
                      rep(c(0.1,0.1,0.1,0.025),numf),
                      .1,.1)) %>%
  iFinishTable(labelsRow=2,labelsCol=3)

## Show the huxtable
tbl2
```

```{r table3}
tables(name="Table3",display=FALSE,
       caption=paste("Total effort and harvest summary for All Fish combined",
                     "by fishery type, month, and day type. Compare this to",
                     "columns A-K of 'ICE CREEL HARVEST' Excel file."))

cat("<br><br>")
cat("<hr>")
cat(tables("Table3"))

# Prepare data.frame for huxtable
tbl1 <- sumExpHarvAll %>%
  dplyr::select(FISHERY,MONTH,DAYTYPE,
                ttlVehFshry,anglersPerInt,ttlAnglers,
                avgAnglerHours,ttlAnglerHours,percSucc,ttlSuccAnglers,
                harvestRate,ttlHarvest) %>%
  dplyr::arrange(FISHERY,MONTH,DAYTYPE) %>%
  # Remove repeated rows in MONTH and FISHERY variables
  dplyr::mutate(
    MONTH=ifelse(!FSA::repeatedRows2Keep(.,cols2use="MONTH"),
                 "",as.character(MONTH)),
    FISHERY=ifelse(!FSA::repeatedRows2Keep(.,cols2use="FISHERY"),
                 "",as.character(FISHERY))) %>%
  ## Remove rows that are repeats (for the numerics) of the row above it and
  ## if DAYTYPE=="All" (i.e., "All" is just for one daytype).
  dplyr::filter(!(!FSA::repeatedRows2Keep(.,
                            cols2ignore=c("FISHERY","MONTH","DAYTYPE")) &
                DAYTYPE=="All"))

    
## Rows with a FISHERY names (except first) will get extra space above
spaceAbove <- which(tbl1$FISHERY!="")[-1]
## Rows with a DAYTYPE=="All" (except lasst) will get extra space below
spaceBelow <- which(tbl1$DAYTYPE=="All")
spaceBelow <- spaceBelow[-length(spaceBelow)]

## Make the huxtable
tbl2 <- as_hux(tbl1) %>%
  # Set all cell paddings
  set_all_padding(1) %>%
  set_right_padding(row=everywhere,col=everywhere,value=5) %>%
  set_top_padding(row=spaceAbove,col=everywhere,value=25) %>%
  set_bottom_padding(row=spaceBelow,col=everywhere,value=5) %>%
  # Convert NAs to dashes
  set_na_string(row=everywhere,col=-(1:3),value="--") %>%
  # right align all but leftmost thre columns
  set_align(row=everywhere,col=-(1:3),value="right") %>%
  # contol decimals
  set_number_format(row=everywhere,col=c(4,6,8,10,12),value=0) %>%
  set_number_format(row=everywhere,col=9,value=1) %>%
  set_number_format(row=everywhere,col=c(5,7),value=2) %>%
  set_number_format(row=everywhere,col=11,value=4) %>%
  # Extra label at the top
  rbind(c("FISHERY","MONTH","DAYTYPE","Vehicles","per Int","Anglers",
          "Hours","Angler Hrs","Success","Anglers","Rate","Harvest"),.) %>%
  rbind(c("","","","Total","Angler","Total",
          "Avg","Total","Perc","Success","Harvest","Total"),.) %>%
  set_align(row=1:2,col=everywhere,value="center") %>%
  # Sets table & column widths
  set_width(0.9) %>%
  set_col_width(col=c(.2,.1,.1,.1,.1,.1,.1,.1,.1,.1,.1,.1)) %>%
  iFinishTable(labelsRow=2,labelsCol=3)
tbl2
```

```{r table4}
tables(name="Table4",display=FALSE,
       caption=paste("Harvest rate and total harvest by species, fishery,",
                     "month, and daytype. Note that 'All' is shown for the",
                     "fishery only for species caught in more than one",
                     "fishery. Compare this to columns L-AD of 'ICE CREEL",
                     "HARVEST' Excel file."))

cat("<br><br>")
cat("<hr>")
cat(tables("Table4"))

# Prepare data.frame for huxtable
## Move DAYTYPEs into columns
H <- select(sumExpHarvSPP,-SURVEY,-ROUTE,-UNIT)
tmp1 <- dplyr::filter(H,DAYTYPE=="Weekday") %>%
  dplyr::select(-DAYTYPE)
tmp2 <- dplyr::filter(H,DAYTYPE=="Weekend") %>%
  dplyr::select(-DAYTYPE)
tmp3 <- dplyr::filter(H,DAYTYPE=="All") %>%
  dplyr::select(-DAYTYPE)
tbl1 <- dplyr::full_join(tmp1,tmp2,by=c("SPECIES","FISHERY","MONTH")) %>%
  dplyr::full_join(tmp3,by=c("SPECIES","FISHERY","MONTH")) %>%
  dplyr::filter(!is.na(SPECIES)) %>%
  dplyr::mutate(SPECIES=factor(SPECIES,levels=lvlsSPECIES)) %>%
  dplyr::arrange(SPECIES,FISHERY,MONTH) %>%
  ## Add aesthetic spacing columns (for huxtable)
  tibble::add_column(.,spc1="",.after="ttlHarvest.x") %>%
  tibble::add_column(.,spc2="",.after="ttlHarvest.y")
## Drop the "All" FISHERYs for species captured in only one fishery
## (note the use of 2 in the filter because of an "All" fishery)
SPP2dropAll <- dplyr::group_by(tbl1,SPECIES) %>%
  dplyr::summarize(numFshrys=length(unique(FISHERY))) %>%
  dplyr::filter(numFshrys==2)
tbl1 <- filter(tbl1,!(SPECIES %in% SPP2dropAll$SPECIES & FISHERY=="All"))
## Drop the "All" MONTHs for species captured in only one month
## (note the use of 2 in the filter because of an "All" MONTH)
SPP2dropAll <- dplyr::group_by(tbl1,SPECIES) %>%
  dplyr::summarize(numMons=length(unique(MONTH))) %>%
  dplyr::filter(numMons==2)
tbl1 <- filter(tbl1,!(SPECIES %in% SPP2dropAll$SPECIES & MONTH=="All"))
## Remove repeated rows in SPECIES, FISHERY, MONTH variables (aesthetics in huxt)
tbl1 <- tbl1 %>%
        dplyr::mutate(SPECIES=ifelse(!FSA::repeatedRows2Keep(.,cols2use="SPECIES"),
                                  "",as.character(SPECIES)),
            ## Use of both SPECIES and FISHERY (rather than just FISHERY) guards
            ## against cutting a FISHERY across species
            FISHERY=ifelse(!FSA::repeatedRows2Keep(.,cols2use=c("SPECIES","FISHERY")),
                           "",as.character(FISHERY)),
            MONTH=ifelse(!FSA::repeatedRows2Keep(.,cols2use=c("SPECIES","MONTH")),
                         "",as.character(MONTH)))
## Rows with a MONTH names (except first) will get extra space above
spaceAbove <- which(tbl1$SPECIES!="")[-1]

## Make the huxtable
tbl2 <- as_hux(tbl1) %>%
  # Set all cell paddings
  set_all_padding(1) %>%
  set_right_padding(row=everywhere,col=everywhere,value=5) %>%
  set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
  # Convert NAs to dashes
  set_na_string(row=everywhere,col=-(1:3),value="--") %>%
  # right align all but leftmost two columns
  set_align(row=everywhere,col=-(1:3),value="right") %>%
  # No decimals for harvest rates, four for harvest rate
  set_number_format(row=everywhere,col=contains("Harvest"),value=0) %>%
  set_number_format(row=everywhere,col=contains("Rate"),value=4) %>%
  # Extra label at the top
  rbind(c("SPECIES","FISHERY","MONTH",rep(c("Rate","Harvest",""),2),
          "Rate","Harvest"),.) %>%
  rbind(c("","","",rep(c("Harvest","Total",""),2),"Harvest","Total"),.) %>%
  rbind(c("","","","Weekdays","","","Weekends","","","All",""),.) %>%
  # Adjust headers
  merge_cells(row=1,col=4:5) %>%
  set_bottom_border(row=1,col=4,value=1) %>%
  merge_cells(row=1,col=7:8) %>%
  set_bottom_border(row=1,col=7,value=1) %>%
  merge_cells(row=1,col=10:11) %>%
  set_bottom_border(row=1,col=10,value=1) %>%
  set_align(row=1,col=everywhere,value="center") %>%
  # Sets table & column widths
  set_width(0.99) %>%
  set_col_width(col=c(.2,.3,.1,.15,.1,.025,.15,.1,.025,.15,.1)) %>%
  iFinishTable(labelsRow=3,labelsCol=3)
tbl2
```

```{r table5}
tables(name="Table5",display=FALSE,
       caption=paste("Number of fish measured for length and mean, standard",
                     "deviation (SD), minimum, and maximum total length",
                     "(in.) by species, month, origin (native or hatchery)",
                     "and fishery type. Note that 'All' is shown only for",
                     "months and origins where more than one month or origin",
                     "was observed. Compare this to 'ICE CREEL CATCH AVE'",
                     "Excel file."))

cat("<br><br>")
cat("<hr>")
cat(tables("Table5"))

## Prepare data.frame for huxtable
fshrys <- unique(sumLen$FISHERY)
numf <- length(fshrys)
bys <- c("SURVEY","ROUTE","UNIT","SPECIES","MONTH","ORIGIN")
tmp1 <- split(sumLen,sumLen$FISHERY)
tmp2 <- dplyr::full_join(tmp1[[1]],tmp1[[2]],by=bys)
for (i in 3:numf) tmp2 <- dplyr::full_join(tmp2,tmp1[[i]],by=bys)

tbl1 <- tmp2 %>%
  dplyr::select(-dplyr::contains("FISHERY"),-SURVEY,-ROUTE,-UNIT) %>%
  dplyr::filter(!duplicated(.)) %>%
  dplyr::mutate(SPECIES=factor(SPECIES,levels=lvlsSPECIES)) %>%
  dplyr::arrange(SPECIES,MONTH,ORIGIN)

## Drop the "All" ORIGINs for species have only one ORIGIN
## (note the use of 2 in the filter because of an "All" ORIGIN)
SPP2dropAll <- dplyr::group_by(tbl1,SPECIES) %>%
  dplyr::summarize(numOrigins=length(unique(ORIGIN))) %>%
  dplyr::filter(numOrigins==2)
tbl1 <- filter(tbl1,!(SPECIES %in% SPP2dropAll$SPECIES & ORIGIN=="All"))

## Drop the "All" MONTHs for species have only one MONTH
## (note the use of 2 in the filter because of an "All" MONTH)
SPP2dropAll <- dplyr::group_by(tbl1,SPECIES) %>%
  dplyr::summarize(numMons=length(unique(MONTH))) %>%
  dplyr::filter(numMons==2)
tbl1 <- filter(tbl1,!(SPECIES %in% SPP2dropAll$SPECIES & MONTH=="All"))

## Remove repeated rows in SPECIES, MONTH and ORIGIN variables
tbl1 <- tbl1 %>%
  dplyr::mutate(SPECIES=ifelse(!FSA::repeatedRows2Keep(.,cols2use="SPECIES"),
                           "",as.character(SPECIES)),
                MONTH=ifelse(!FSA::repeatedRows2Keep(.,cols2use=c("SPECIES","MONTH")),
                             "",as.character(MONTH)))

## Add extra columns for aesthetics in huxtable
acs <- which(grepl("maxLen",names(tbl1)))
for (i in rev(acs[-length(acs)])) {
  tbl1 <- tibble::add_column(tbl1,"",.after=i)
  names(tbl1)[i+1] <- paste0("spc",i)
}

spaceAbove <- which(tbl1$SPECIES!="")[-1]

toplbl <- c("","","")
for (i in fshrys) toplbl <- c(toplbl,i,"","","","","")
toplbl <- toplbl[-length(toplbl)]

tbl2 <- as_hux(tbl1) %>%
  # Set all cell paddings
  set_all_padding(1) %>%
  set_right_padding(row=everywhere,col=everywhere,value=5) %>%
  set_top_padding(row=spaceAbove,col=everywhere,value=15) %>%
  # Convert NAs to dashes
  set_na_string(row=everywhere,col=-(1:3),value="--") %>%
  # right align all but leftmost three columns
  set_align(row=everywhere,col=-(1:3),value="right") %>%
  # Set decimals
  set_number_format(row=everywhere,col=starts_with("n"),value=0) %>%
  set_number_format(row=everywhere,col=contains("Len"),value=1) %>%
  # Extra label at the top
  rbind(c("SPECIES","MONTH","ORIGIN",
          rep(c("n","Mean","SD","Min","Max",""),numf-1),
          "n","Mean","SD","Min","Max"),.) %>%
  rbind(toplbl,.)
# Adjust headers
for (i in 1:numf) {
  cols <- (4:8)+(i-1)*6
  tbl2 <- merge_cells(tbl2,row=1,col=cols) %>%
    set_bottom_border(row=1,col=cols[1],value=1)
}
tbl2 <- tbl2 %>%
  set_align(row=1,col=everywhere,value="center") %>%
  # Sets table & column widths
  set_width(0.99) %>%
  set_col_width(col=c(.2,.1,.1,
                      rep(c(0.1,0.1,0.1,0.1,0.1,0.025),numf-1),
                      0.1,0.1,0.1,0.1,0.1)) %>%
  iFinishTable(labelsRow=2,labelsCol=3)
tbl2
```



```{r}
cat("<br><br>")
cat("<hr>")
FSA::reproInfo(out="markdown",rqrdPkgs=rqrd,addTOC=FALSE)
```
