---
title: "Lake Superior Creel Scheduler"

output: 
  pdf_document:
    includes:
      in_header: LS_Scheduler_Preamble.tex
params:
  YEAR: 
    value: 2019
  CLERK: 
    value: A
  LAKE:
    value: "Superior"
  SEED:
    value: NULL
  SCHED:
    value: ""
  WDIR:
    value: ""
---

\fontsize{14}{18}
\selectfont
\pagenumbering{gobble}

```{r input, echo=FALSE}
## Grab User's Inputs from parameters
LAKE <- params$LAKE
YEAR <- params$YEAR
CLERK <- params$CLERK
SEED <- params$SEED
SCHED <- params$SCHED
WDIR <- params$WDIR
```

```{r setup, include=FALSE, message=FALSE}
## Preliminaries
try(detach("package:kableExtra",unload=TRUE),silent=TRUE)
suppressPackageStartupMessages(library(kableExtra))
source(paste0(WDIR,"Helpers/LS_Scheduler_Helpers.R"))
knitr::opts_chunk$set(echo = FALSE)

## Set the random number seed
if (!is.null(SEED)) set.seed(SEED)

## Read the schedule
sched <- readSchedule(SCHED,WDIR,show_summary=FALSE,show_calendars=FALSE)

## Get routes for this clerk
ROUTES <- unique(sched$ROUTE[complete.cases(sched$ROUTE)])
```

**Year:** `r YEAR`

\vspace{12pt}

**Lake:** `r LAKE`

**Clerk:** `r CLERK`

**Route(s):** `r paste0(ROUTES,collapse=" and ")`

\vspace{12pt}

**Ran:** `r format(lubridate::now(),format="%d-%b-%Y at %H:%M")`

**Seed:** `r ifelse(is.null(SEED),"None used",formatC(SEED,format="d"))`

\textbf{Schedule File:} `r gsub("_","\\_",basename(SCHED),fixed=TRUE)`

\textbf{Folder} `r RDIR`

```{r makeCalendars, echo=FALSE, fig.width=7, fig.height=7, fig.show="asis", }
## Print monthly calendars
mos <- as.character(unique(sched$MONTH))
for (i in mos) makeCalendar(sched,MONTH1=i,WDIR,
                            header="Lake Superior Creel Schedule")
```

\newpage

```{r makeBusRoute, results='asis'}
## Read in Route and Shift information
finfo <- readInfo(CLERK,WDIR)
## Print bus routes if more than one site is visited
sites <- unique(finfo$routes$site)
if (length(sites)>1) {
  ## Print the bus routes
  for (i in mos) {
    tmp <- dplyr::filter(sched,MONTH==i,CREEL=="YES")
    for (j in seq_len(nrow(tmp))) {
      tmp_j <- tmp[j,]
      br <- iMakeBusRoute(finfo,ROUTE=tmp_j$ROUTE,SHIFT=tmp_j$SHIFT,
                          MONTH1=tmp_j$MONTH)
      cat("\\newpage\n")
      cat(paste0("**Lake ",FSA::capFirst(LAKE)," Creel Survey**\n\n"))
      cat(paste0("**#",tmp_j$DAILY_SCHED,": ",tmp_j$ROUTE," route for ",
                format(lubridate::ymd(tmp_j$DATE),format="%m/%d/%Y")," -- ",
                FSA::capFirst(tmp_j$DAYTYPE),
                ifelse(tmp_j$DAYTYPE=="WEEKDAY"," (1)"," (2)"),
                ", ",tmp_j$SHIFT," shift**"))
      cat("\\vspace{24pt}\n")
      print(iPrintBusRoute(br))
      cat("\\vspace{24pt}\n")
      cat("**NOTES:**")
    }
  }
}
```
