---
title: "Lake Superior Creel Scheduler"
header-includes:
   - \usepackage{booktabs}
   - \usepackage[table]{xcolor}
   - \usepackage{colortbl}
output: 
  pdf_document:
    includes:
      in_header: preamble.tex
params:
  YEAR: 
    value: 2019
    input: slider
    min: 2019
    max: 2025
    step: 1
  CLERK: 
    value: A
    input: select
    choices: [A,B,C,D]
  SEED:
    value: 34534
---

\fontsize{14}{18}
\selectfont
\pagenumbering{gobble}

```{r input, echo=FALSE}
## Grab User's Inputs from parameters
YEAR <- params$YEAR
CLERK <- params$CLERK
SEED <- params$SEED
LAKE <- "SUPERIOR"
```

```{r setup, include=FALSE, message=FALSE}
fldr <- ""
source(paste0(fldr,"Schedule_Helpers.R"))
knitr::opts_chunk$set(echo = FALSE)

## Read in Route and Shift information
finfo <- paste0(fldr,"Schedule_Info_LS.xlsx")
## Load route and shift information
clerks <- readClerks(finfo,"Clerks",CLERK)
routes <- readRoutes(finfo,"Routes",clerks)
shifts <- readShifts(finfo,"Shifts",clerks)

## Get Routes for this Clerk
ROUTE <- unique(routes$route)

## Set the random number seed
if (!is.null(SEED)) set.seed(SEED)

## Set filename for schedule data
fout <- paste(YEAR,toupper(LAKE),paste0(ROUTE,collapse="_"),"schedule.csv",sep="_")
```

**Year:** `r YEAR`

\vspace{12pt}

**Lake:** `r LAKE`

**Clerk:** `r CLERK`

**Route(s):** `r paste0(ROUTE,collapse=" and ")`

\vspace{12pt}

**Ran:** `r format(lubridate::now(),format="%d-%b-%Y at %H:%M")`

**Seed:** `r formatC(SEED,format="d")`

\textbf{Schedule File:} `r gsub("_","\\_",fout,fixed=TRUE)`

```{r makeSchedule, include=FALSE}
## Make the schedule
sched <- makeSchedule(LAKE,YEAR,routes,clerks,fout)
```

\newpage

```{r makeBusRoute, echo=FALSE, fig.width=7, fig.height=7, fig.show="asis", results="asis"}
## Print monthly calendars
mos <- as.character(unique(sched$MONTH))
for (i in mos) makeCalendar(sched,MONTH1=i)

## Print the bus routes
for (i in mos) {
  tmp <- dplyr::filter(sched,MONTH==i,CREEL=="YES")
  for (j in seq_len(nrow(tmp))) {
    br <- iMakeBusRoute(routes,shifts,
                        ROUTE=as.character(tmp$ROUTE[j]),
                        SHIFT=as.character(tmp$SHIFT[j]),
                        MONTH1=as.character(tmp$MONTH[j]))
    cat("\\newpage\n")
    print(iPrintBusRouteHeader(tmp[j,]))
    cat("\\vspace{24pt}\n")
    print(iPrintBusRoute(br))
  }
}

```
