/* 9/20/90 VERSION - INCLUDES CORRECTION TO PRODUCE SINGLE RANDOM*/
/* NUMBER STREAM - REPLACES ALL OLDER VERSION OF CRANSKED        */
%MACRO LOCS;
DATA LOCS;
LENGTH LOCATION $ 30;
INPUT MINS LOCATION $30.;
RETAIN START;
IF _N_=1 THEN START=0;
STOP=START+MINS-1;
DO TEMP=START TO STOP;
  KEEP TEMP LOCATION;
  OUTPUT;
END;
START=STOP+1;
%MEND LOCS;

%MACRO RAND;
  TEMPSEED=1;
  TEMPSEED=SYMGET('SEED');
  CALL RANUNI(TEMPSEED,RANDOM);
  CALL SYMPUT('SEED',TEMPSEED);
  IF RANDOM GT 1.0 THEN DO;
    PUT 'SEED TOO LARGE';
    ABORT;
  END;
%MEND RAND;

%MACRO SKEDULE;
DATA SKEDULE;
OPTIONS NODATE NONUMBER;
DO N=1 TO &RANNUM;
  IF &STOP GT &START THEN SHIFTLEN=(&STOP-&START)/60;
  ELSE SHIFTLEN=('24:00'T-&START+&STOP)/60;
  TIME=&START;
  %RAND
  STARTLOC=INT(RANDOM*SHIFTLEN);
  %RAND;
  IF RANDOM GT 0.5 THEN DIR=1; ELSE DIR=-1;
  STOPLOC=STARTLOC+(DIR*SHIFTLEN)-DIR;
  DO I=STARTLOC TO STOPLOC BY DIR;
    MULT=ABS(INT(I/SHIFTLEN));
    IF I LT 0 THEN MULT=MULT+1;
    TEMP=I-(MULT*DIR*SHIFTLEN);
    KEEP N TIME TEMP;
    OUTPUT;
    TIME=TIME+60;
  END;
END;

PROC SORT;
BY TEMP N;

DATA SKEDULE;
MERGE SKEDULE(IN=A) LOCS(IN=B);
BY TEMP;
IF A AND B;
KEEP N TIME LOCATION;

PROC SORT;
BY N TIME;

DATA SKEDULE;
SET SKEDULE;
BY N LOCATION NOTSORTED;
IF FIRST.LOCATION;
TIME1='__ __:__ __   ';    
TIME2='__ __:__ __   ';   
COUNT1='__ __ __';   ;
*COUNT2='__ __ __';
IF LOCATION='TRAVEL' THEN DO;
  TIME1=' ';
  TIME2=' ';    
  COUNT1=' '; 
 * COUNT2=' ';
END;

DATA SKEDULE;
SET SKEDULE;
IF TIME GE '24:00'T THEN TIME=TIME-'24:00'T;
BY N;
OUTPUT;
IF LAST.N THEN DO;
  TIME=&STOP;
  LOCATION='END OF SHIFT';
  TIME1=' ';    
  TIME2=' ';    
  COUNT1=' ';    
  *COUNT2=' ';
  OUTPUT;
END;
LABEL TIME1='TIME ARRIVED'
      TIME2='TIME DEPARTED'
      COUNT1='WEIGHTED COUNT';
   *   COUNT2='PARTIES COMPLETING TRIPS';
TITLE3 ' ';
TITLE4 'DATE (MM/DD/YYYY):   __ __ /__ __ /__ __ __ __
WEEKDAY (1)     WEEKEND/HOLIDAY (2)';

PROC PRINT SPLIT=' ';
FORMAT TIME TIME5.;
BY N;
PAGEBY N;
ID TIME;
VAR LOCATION TIME1 TIME2 COUNT1;* COUNT2;
%MEND SKEDULE;
